#include <iostream>
#include "AsioHttps.h"
#include <boost/bind.hpp>
void callback(std::shared_ptr<HttpRequestMsgStruct> request, std::shared_ptr<HttpResponseMsgStruct> response, int addtion){
  if(response->error_ == ""){
    //std::cout<<response->str_ori_<<std::endl;
    std::cout<<"get response success!"<<request->head_.GetAttribute("host")<<",addtion:"<<addtion<<std::endl;
  }else{
    std::cout<<"get response faild:"<<request->head_.GetAttribute("host")<<response->error_<<std::endl;
  }
}

int main(){
  std::cout<<"hello world!"<<std::endl;
  AsioHttps https(4);
  std::shared_ptr<AsioHttpsSocket> socket = https.CreateAsioHttpSocket();
  {
    std::shared_ptr<AsioHttpsRequest> request = std::make_shared<AsioHttpsRequest>();
    request->config_.ssl_ = true;
    request->config_.use_proxy_ = true;
    request->config_.websocket_ = true;
    request->config_.proxy_.url_ = "127.0.0.1";
    request->config_.proxy_.port_ = 1080;
    request->head_.DeleteAllAttribute();
    request->head_.SetAttribute("host", "api.huobi.pro");
    request->head_.SetAttribute("Origin", "wss://api.huobi.pro");
    request->head_.SetAttribute("Upgrade", "websocket");
    request->head_.SetAttribute("Connection", "Upgrade");
    request->head_.SetAttribute("Sec-WebSocket-Key", "x3JJHMbDL1EzLkh9GBhXDw==");
    request->head_.SetAttribute("Sec-WebSocket-Version", "13");
    request->head_.url_ = "/ws";
    /*request->body_="{\
                   \"sub\": \"market.btcusdt.trade.detail\",\
                   \"id\": \"id generated by client\"\
                 }";*/
    socket->Process(request, boost::bind(callback,_1,_2, 1));
  }
#if 0
  {
    ProxyConfig config;
    config.url_ = "127.0.0.1";
    config.port_ = 1080;

    socket->Process("https://www.google.com/"
                     , config
                     , boost::bind(callback,_1,_2, 1));
  }

  {
    ProxyConfig config;
    config.url_ = "127.0.0.1";
    config.port_ = 1080;

    socket->Process("http://www.sohu.com/"
                     , config
                     , boost::bind(callback,_1,_2, 2));
  }
  {
    ProxyConfig config;
    config.url_ = "127.0.0.1";
    config.port_ = 1080;

    socket->Process("http://www.sohu.com/"
                     , config
                     , boost::bind(callback,_1,_2, 3));
  }

  {
    socket->Process("http://www.sohu.com/"
                     , boost::bind(callback,_1,_2, 4));
  }

  {
    socket->Process("https://www.baidu.com/"
                     , boost::bind(callback,_1,_2, 5));
  }

  std::shared_ptr<AsioHttpsSocket> socket_muti[100];
  for(int i = 0; i < 100; i++){
    socket_muti[i] = https.CreateAsioHttpSocket();
    socket_muti[i]->Process("http://www.sohu.com/"
                            , boost::bind(callback,_1,_2, 6+i));
  }
#endif
  getchar();
  exit(0);
  return 0;
}
